version: "3.7"

services:
  database:
    image: postgres
    container_name: test_mevo
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker123
      - POSTGRES_DB=orders
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
